default: &default
  adapter: sqlserver
  encoding: utf8
  timeout: 15000

wlm: &wlm
  <<: *default
  host: WM11162.local
  port: 1433
  database: Pris
  username: 
  password: 
  tds_version: 70

development:
  <<: *wlm

test:
  <<: *default

production:
  <<: *wlm
