IF OBJECT_ID(N'[dbo].[CountryCode]', N'U') IS NOT NULL DROP TABLE [dbo].[CountryCode];
CREATE TABLE [dbo].[CountryCode]([COUNTRY_CODE] [char](2) NOT NULL, [COUNTRY_NAME] [varchar](32) NULL, [OFFICIAL_NAME] [varchar](64) NULL, CONSTRAINT [PK_CountryCode] PRIMARY KEY ([COUNTRY_CODE] ASC));
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'AD', N'Andorra                         ', N'Principality of Andorra');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'AE', N'United Arab Emirates            ', N'United Arab Emirates');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'AF', N'Afghanistan                     ', N'Islamic State of Afghanistan');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'AG', N'Antigua and Barbuda             ', N'Antigua and Barbuda');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'AI', N'Anguilla                        ', N'Anguilla');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'AL', N'Albania                         ', N'Republic of Albania');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'AM', N'Armenia                         ', N'Republic of Armenia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'AN', N'Netherlands Antilles            ', N'Netherlands Antilles');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'AO', N'Angola                          ', N'Republic of Angola');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'AQ', N'Antarctica                      ', N'Antarctica');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'AR', N'Argentina                       ', N'Argentine Republic');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'AS', N'American Samoa                  ', N'American Samoa');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'AT', N'Austria                         ', N'Republic of Austria');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'AU', N'Australia                       ', N'Australia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'AW', N'Aruba                           ', N'Aruba');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'AZ', N'Azerbaijan                      ', N'Azerbaijani Republic');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'BA', N'Bosnia and Herzegovina          ', N'Republic of Bosnia and Herzegovina');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'BB', N'Barbados                        ', N'Barbados');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'BD', N'Bangladesh                      ', N'People''s Republic of Bangladesh');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'BE', N'Belgium                         ', N'Kingdom of Belgium');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'BF', N'Burkina Faso                    ', N'Burkina Faso');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'BG', N'Bulgaria                        ', N'Republic of Bulgaria');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'BH', N'Bahrain                         ', N'State of Bahrain');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'BI', N'Burundi                         ', N'Republic of Burundi');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'BJ', N'Benin                           ', N'Republic of Benin');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'BM', N'Bermuda                         ', N'Bermuda');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'BN', N'Brunei Darussalam               ', N'Brunei Darussalam');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'BO', N'Bolivia                         ', N'Republic of Bolivia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'BR', N'Brazil                          ', N'Federative Republic of Brazil');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'BS', N'Bahamas                         ', N'Commonwealth of the Bahamas');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'BT', N'Bhutan                          ', N'Kingdom of Bhutan');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'BV', N'Bouvet Island                   ', N'Bouvet Island');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'BW', N'Botswana                        ', N'Republic of Botswana');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'BY', N'Belarus                         ', N'Republic of Belarus');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'BZ', N'Belize                          ', N'Belize');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'CA', N'Canada                          ', N'Canada');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'CC', N'Cocos (Keeling) Islands         ', N'Cocos (Keeling) Islands');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'CD', N'Republic of Congo               ', N'The Democratic Republic of the Congo');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'CF', N'Central African Republic        ', N'Central African Republic');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'CG', N'Congo                           ', N'Republic of the Congo');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'CH', N'Switzerland                     ', N'Swiss Confederation');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'CI', N'Ivory Coast                     ', N'Rebuplic of Ivory Coast');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'CK', N'Cook Islands                    ', N'Cook Islands');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'CL', N'Chile                           ', N'Republic of Chile');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'CM', N'Cameroon                        ', N'Republic of Cameroon');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'CN', N'China                           ', N'People''s Republic of China');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'CO', N'Colombia                        ', N'Republic of Colombia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'CR', N'Costa Rica                      ', N'Republic of Costa Rica');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'CU', N'Cuba                            ', N'Republic of Cuba');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'CV', N'Cape Verde                      ', N'Republic of Cape Verde');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'CX', N'Christmas Island                ', N'Christmas Island');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'CY', N'Cyprus                          ', N'Republic of Cyprus');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'CZ', N'Czech Republic                  ', N'Czech Republic');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'DE', N'Germany                         ', N'Federal Republic of Germany');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'DJ', N'Djibouti                        ', N'Republic of Djibouti');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'DK', N'Denmark                         ', N'Kingdom of Denmark');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'DM', N'Dominica                        ', N'Commonwealth of Dominica');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'DO', N'Dominican Republic              ', N'Dominican Republic');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'DZ', N'Algeria                         ', N'People''s Democratic Republic of Algeria');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'EC', N'Ecuador                         ', N'Republic of Ecuador');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'EE', N'Estonia                         ', N'Republic of Estonia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'EG', N'Egypt                           ', N'Arab Republic of Egypt');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'EH', N'Western Sahara                  ', N'Western Sahara');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'ER', N'Eritrea                         ', N'Eritrea');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'ES', N'Spain                           ', N'Kingdom of Spain');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'ET', N'Ethiopia                        ', N'Ethiopia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'FI', N'Finland                         ', N'Republic of Finland');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'FJ', N'Fiji                            ', N'Republic of Fiji');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'FK', N'Falkland Islands (Malvinas)     ', N'Falkland Islands (Malvinas)');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'FM', N'Micronesia                      ', N'Federated States of Micronesia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'FO', N'Faroe Islands                   ', N'Faroe Islands');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'FR', N'France                          ', N'French Republic');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'FX', N'France, Metropolitan            ', N'France, Metropolitan');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'GA', N'Gabon                           ', N'Gabonese Republic');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'GB', N'United Kingdom                  ', N'United Kingdom of Great Britain and North Ireland');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'GD', N'Grenada                         ', N'Grenada');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'GE', N'Georgia                         ', N'Republic of Georgia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'GF', N'French Guiana                   ', N'Department of Guiana');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'GH', N'Ghana                           ', N'Republic of Ghana');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'GI', N'Gibraltar                       ', N'Gibraltar');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'GL', N'Greenland                       ', N'Greenland');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'GM', N'Gambia                          ', N'Republic of the Gambia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'GN', N'Guinea                          ', N'Republic of Guinea');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'GP', N'Guadeloupe                      ', N'Department of Guadeloupe');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'GQ', N'Equatorial Guinea               ', N'Republic of Equatorial Guinea');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'GR', N'Greece                          ', N'Hellenic Republic');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'GS', N'South Georgia/So Sandwich Isl   ', N'South Georgia and the South Sandwich Islands');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'GT', N'Guatemala                       ', N'Republic of Guatemala');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'GU', N'Guam                            ', N'Guam');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'GW', N'Guinea-Bissau                   ', N'Republic of Guinea-Bissau');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'GY', N'Guyana                          ', N'Republic of Guyana');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'HK', N'Hong Kong                       ', N'Hong Kong');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'HM', N'Heard Island & McDonald Isl     ', N'Heard Island & McDonald Isl');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'HN', N'Honduras                        ', N'Republic of Honduras');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'HR', N'Croatia                         ', N'Republic of Croatia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'HT', N'Haiti                           ', N'Republic of Haiti');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'HU', N'Hungary                         ', N'Republic of Hungary');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'ID', N'Indonesia                       ', N'Republic of Indonesia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'IE', N'Ireland                         ', N'Ireland');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'IL', N'Israel                          ', N'State of Israel');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'IN', N'India                           ', N'Republic of India');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'IO', N'British Indian Ocean Territory  ', N'British Indian Ocean Territory');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'IQ', N'Iraq                            ', N'Republic of Iraq');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'IR', N'Iran                            ', N'Islamic Republic of Iran');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'IS', N'Iceland                         ', N'Republic of Iceland');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'IT', N'Italy                           ', N'Italian Republic');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'JM', N'Jamaica                         ', N'Jamaica');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'JO', N'Jordan                          ', N'Hashemite Kingdom of Jordan');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'JP', N'Japan                           ', N'Japan');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'KE', N'Kenya                           ', N'Republic of Kenya');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'KG', N'Kyrgyzstan                      ', N'Kyrgyz Republic');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'KH', N'Cambodia                        ', N'Kingdom of Cambodia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'KI', N'Kiribati                        ', N'Kiribati');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'KM', N'Comoros                         ', N'Islamic Federal Republic of theComoros');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'KN', N'Saint Kitts And Nevis           ', N'Saint Kitts And Nevis');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'KP', N'Korea, North                    ', N'Democratic People''s Republic of Korea');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'KR', N'Korea, South                    ', N'Republic of Korea');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'KW', N'Kuwait                          ', N'State of Kuwait');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'KY', N'Cayman Islands                  ', N'Cayman Islands');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'KZ', N'Kazakhstan                      ', N'Republic of Kazakhstan');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'LA', N'Laos                            ', N'Lao People''s Democratic Republic');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'LB', N'Lebanon                         ', N'Lebanese Republic');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'LC', N'Saint Lucia                     ', N'Saint Lucia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'LI', N'Liechtenstein                   ', N'Principality of Liechtenstein');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'LK', N'Sri Lanka                       ', N'Democratic Socialist Republic of Sri Lanka');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'LR', N'Liberia                         ', N'Republic of Liberia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'LS', N'Lesotho                         ', N'Kingdom of Lesotho');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'LT', N'Lithuania                       ', N'Republic of Lithuania');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'LU', N'Luxembourg                      ', N'Grand Duchy of Luxembourg');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'LV', N'Latvia                          ', N'Republic of Latvia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'LY', N'Libyan Arab Jamahiriya          ', N'Socialist People''s Libyan Arab Jamahiriya');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'MA', N'Morocco                         ', N'Kingdom of Morocco');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'MC', N'Monaco                          ', N'Principality of Monaco');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'MD', N'Moldova                         ', N'Republic of Moldova');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'MG', N'Madagascar                      ', N'Republic of Madagascar');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'MH', N'Marshall Islands                ', N'Republic of the Marshall Islands');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'MK', N'Macedonia                       ', N'The Former republic of Yugoslav');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'ML', N'Mali                            ', N'Republic of Mali');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'MM', N'Myanmar                         ', N'Union of Myanmar');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'MN', N'Mongolia                        ', N'Mongolia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'MO', N'Macau                           ', N'Macau');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'MP', N'Northern Mariana Islands        ', N'Commonwealth of the Northern Mariana Islands');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'MQ', N'Martinique                      ', N'Department of Martinique');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'MR', N'Mauritania                      ', N'Islamic Republic of Mauritania');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'MS', N'Montserrat                      ', N'Montserrat');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'MT', N'Malta                           ', N'Republic of Malta');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'MU', N'Mauritius                       ', N'Republic of Mauritius');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'MV', N'Maldives                        ', N'Republic of Maldives');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'MW', N'Malawi                          ', N'Republic of Malawi');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'MX', N'Mexico                          ', N'United Mexican States');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'MY', N'Malaysia                        ', N'Malaysia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'MZ', N'Mozambique                      ', N'Republic of Mozambique');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'NA', N'Namibia                         ', N'Republic of Namibia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'NC', N'New Caledonia                   ', N'New Caledonia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'NE', N'Niger                           ', N'Republic of the Niger');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'NF', N'Norfolk Island                  ', N'Norfolk Island');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'NG', N'Nigeria                         ', N'Federal Republic of Nigeria');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'NI', N'Nicaragua                       ', N'Republic of Nicaragua');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'NL', N'Netherlands                     ', N'Kingdom of the Netherlands');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'NO', N'Norway                          ', N'Kingdom of Norway');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'NP', N'Nepal                           ', N'Kingdom of Nepal');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'NR', N'Nauru                           ', N'Republic of Nauru');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'NU', N'Niue                            ', N'Niue');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'NZ', N'New Zealand                     ', N'New Zealand');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'OM', N'Oman                            ', N'Sultanate of Oman');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'PA', N'Panama                          ', N'Republic of Panama');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'PE', N'Peru                            ', N'Republic of Peru');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'PF', N'French Polynesia                ', N'French Polynesia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'PG', N'Papua New Guinea                ', N'Papua New Guinea');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'PH', N'Philippines                     ', N'Republic of the Philippines');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'PK', N'Pakistan                        ', N'Islamic Republic of Pakistan');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'PL', N'Poland                          ', N'Republic of Poland');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'PM', N'Saint Pierre And Miquelon       ', N'Territorial collectivity of St. Pierre & Miquelon');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'PN', N'Pitcairn                        ', N'Pitcairn');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'PR', N'Puerto Rico                     ', N'Puerto Rico');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'PS', N'Palestine                       ', N'Palestinian Territory Occupied');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'PT', N'Portugal                        ', N'Portuguese Republic');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'PW', N'Palau                           ', N'Republic of Palau');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'PY', N'Paraguay                        ', N'Republic of Paraguay');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'QA', N'Qatar                           ', N'State of Qatar');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'RE', N'Reunion                         ', N'Department of Reunion');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'RO', N'Romania                         ', N'Romania');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'RU', N'Russian Federation              ', N'Russian Federation');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'RW', N'Rwanda                          ', N'Rwandese Republic');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'SA', N'Saudi Arabia                    ', N'Kingdom of Saudi Arabia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'SB', N'Solomon Islands                 ', N'Solomon Islands');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'SC', N'Seychelles                      ', N'Republic of Seychelles');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'SD', N'Sudan                           ', N'Republic of the Sudan');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'SE', N'Sweden                          ', N'Kingdom of Sweden');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'SG', N'Singapore                       ', N'Republic of Singapore');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'SH', N'Saint Helena                    ', N'Saint Helena');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'SI', N'Slovenia                        ', N'Republic of Slovenia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'SJ', N'Svalbard and Jan Mayen          ', N'Svalbard and Jan Mayen');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'SK', N'Slovakia                        ', N'Slovak Republic');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'SL', N'Sierra Leone                    ', N'Republic of Sierra Leone');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'SM', N'San Marino                      ', N'Republic of San Marino');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'SN', N'Senegal                         ', N'Republic of Senegal');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'SO', N'Somalia                         ', N'Somali Democratic Republic');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'SR', N'Suriname                        ', N'Republic of Suriname');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'ST', N'Sao Tome and Principe           ', N'Democratic Republic of Sao Tome and Principe');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'SV', N'El Salvador                     ', N'Republic of El Salvador');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'SY', N'Syrian Arab Republic            ', N'Syrian Arab Republic');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'SZ', N'Swaziland                       ', N'Kingdom of Swaziland');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'TC', N'Turks and Caicos Islands        ', N'Turks and Caicos Islands');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'TD', N'Chad                            ', N'Republic of Chad');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'TF', N'French Southern Territories     ', N'French Southern Territories');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'TG', N'Togo                            ', N'Togolese Republic');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'TH', N'Thailand                        ', N'Kingdom of Thailand');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'TJ', N'Tajikistan                      ', N'Republic of Taiikistan');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'TK', N'Tokelau                         ', N'Tokelau');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'TM', N'Turkmenistan                    ', N'Turkmenistan');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'TN', N'Tunisia                         ', N'Republic of Tunisia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'TO', N'Tonga                           ', N'Kingdom of Tonga');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'TP', N'East Timor                      ', N'East Timor');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'TR', N'Turkey                          ', N'Republic of Turkey');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'TT', N'Trinidad and Tobago             ', N'Republic of Trinidad and Tobago');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'TV', N'Tuvalu                          ', N'Tuvalu');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'TW', N'Taiwan                          ', N'Taiwan, Province of China');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'TZ', N'Tanzania                        ', N'United Republic of Tanzania');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'UA', N'Ukraine                         ', N'Ukraine');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'UG', N'Uganda                          ', N'Republic of Uganda');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'UM', N'US Minor Outlying Islands       ', N'US Minor Outlying Islands');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'US', N'United States                   ', N'United States of America');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'UY', N'Uruguay                         ', N'Eastern Republic of Uruguay');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'UZ', N'Uzbekistan                      ', N'Republic of Uzbekistan');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'VA', N'Vatican City State              ', N'Vatican City State');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'VC', N'Saint Vincent & the Grenadines  ', N'Saint Vincent & the Grenadines');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'VE', N'Venezuela                       ', N'Republic of Venezuela');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'VG', N'Virgin Islands (British)        ', N'Virgin Islands (British)');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'VI', N'Virgin Islands (U.S.)           ', N'Virgin Islands of the United States');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'VN', N'Viet Nam                        ', N'Socialist Republic of Viet Nam');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'VU', N'Vanuatu                         ', N'Republic of Vanuatu');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'WF', N'Wallis and Futuna Islands       ', N'Wallis and Futuna Islands');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'WS', N'Samoa                           ', N'Independent State of Western Samoa');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'YE', N'Yemen                           ', N'Republic of Yemen');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'YT', N'Mayotte                         ', N'Territorial collectivity of Mayotte');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'YU', N'Yugoslavia                      ', N'Federal Republic of Yugoslavia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'ZA', N'South Africa                    ', N'Republic of South Africa');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'ZM', N'Zambia                          ', N'Republic of Zambia');
INSERT [dbo].[CountryCode] ([COUNTRY_CODE], [COUNTRY_NAME], [OFFICIAL_NAME]) VALUES (N'ZW', N'Zimbabwe                        ', N'Republic of Zimbabwe');
